---
- name: create workstation
  hosts: localhost
  vars_prompt:
    - name: ansible_user
      prompt: What is the username
      private: no
  roles:
    - { role: ned300889.bootstrap, become: yes }
    - { role: ned300889.utilities, become: yes }
    - { role: ned300889.cri-o, become: yes}